steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
  env: ['DATABASE_NAME=$$DATABASE_NAME','JDBC_PASSWORD=$$JDBC_PASSWORD','JDBC_SCHEMA=$$JDBC_SCHEMA','JDBC_URL=$$JDBC_URL','JDBC_USERNAME=$$JDBC_USERNAME']
  secretEnv: ['DATABASE_NAME', 'JDBC_PASSWORD', 'JDBC_USERNAME', 'JDBC_URL', 'JDBC_SCHEMA']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/project2-251819/github.com', '.']
images: ['gcr.io/project2-251819/github.com']

secrets:
- kmsKeyName: 'projects/project2-251819/locations/global/keyRings/db_keyring/cryptoKeys/db_key'
  secretEnv:
    DATABASE_NAME: 'CiQAXCcwx8E+EGfBl1Vq30tl17GLlBLaQSRsuENEZaeopaDp6+kSMgAQAZBNdoWcw2Y+D4UrIJF+
RtyyKhmbF8gXoihSX9KrCNc6ka8ib4d/kpoPsDT5G3yh'
    JDBC_URL: 'CiQAXCcwx9Q8rQKMxL4zvckIRbCqzw95ZBbyWWu9BLM3137593MSNQAQAZBNcfvAB6HBsRjz1jYs
fSMk+nu7RyFkh2enhdixyRzzNO4O/D9r83C+/aGMF6QTX+aB'
    JDBC_SCHEMA: 'CiQAXCcwx2I0h2pJ1ee6D+UF/IqN7jHSdMXd6Ttv+mCWN8G1gnwSMgAQAZBNB4CBDasVFeKhQRJP
vEZPkyR+DHDV8QcraAFR1lXX5u4Z7zIG+I0LZySsDG3W'
    JDBC_USERNAME: 'CiQAXCcwx6Y4up7e18xteWfXdISKb9dEnkbvUHSCnBQ0KMdt7Q0SLAAQAZBNmeM3nr66wpiP6wYq
7AaMqaqLsRAiQeXAZ8niwdXwkrD2iSNGRlXL'
    JDBC_PASSWORD: 'CiQAXCcwxz0UqXJ0vmgRVz1a7Ctyw2kAINZPWtptWMI433j+AigSLAAQAZBNDMpEtDxaa4TTg8H4
3LmUnlMfDxDxGjyGW9er7hRX7vsiRQKBF+bT'
