steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
  env: ['DATABASE_NAME=recipease','JDBC_PASSWORD=abc','JDBC_SCHEMA=recipease','JDBC_URL=34.70.51.191','JDBC_USERNAME=abc']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/project2-251819/github.com', '.']
images: ['gcr.io/project2-251819/github.com']
