FROM maven:3.3.9-jdk-8-alpine as build-env

#ARG DATABASE_NAME
ENV DATABASE_NAME=recipease #${DATABASE_NAME}

ARG JDBC_SCHEMA
ENV JDBC_SCHEMA=recipease #${JDBC_SCHEMA}

ARG JDBC_URL
ENV JDBC_URL=34.70.51.191 #${JDBC_URL}

ARG JDBC_USERNAME
ENV JDBC_USERNAME=abc #${JDBC_USERNAME}

ARG JDBC_PASSWORD
ENV JDBC_PASSWORD=123 #${JDBC_PASSWORD}

COPY . .
RUN mvn install
CMD ['java', '-jar', 'target/Recipease-0.0.1-SNAPSHOT.jar']
